apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-2-minutes
  namespace: backend
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              image: ghcr.io/shashax42/batch-order:sha-1de94be@sha256:e20699b74921fc5c1482f5600b14242d1e1b73e5ac75cf1d3e4e59786adb6169
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "cancelOrderWhereStateIsPendingJob"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-5-minutes
  namespace: backend
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              image: ghcr.io/shashax42/batch-order:sha-1de94be@sha256:e20699b74921fc5c1482f5600b14242d1e1b73e5ac75cf1d3e4e59786adb6169
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "deleteOrderWhereStateIsCanceledJob"
          restartPolicy: OnFailure