apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-2-minutes
  namespace: backend
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              image: ghcr.io/shashax42/batch-order:sha-54ec83c@sha256:341bda07e8948b2df53e900f8484b5e1869076a34955a4ffbc416a14fff3b6cd
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "cancelOrderWhereStateIsPendingJob"
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-order-every-5-minutes
  namespace: backend
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-order
              image: ghcr.io/shashax42/batch-order:sha-54ec83c@sha256:341bda07e8948b2df53e900f8484b5e1869076a34955a4ffbc416a14fff3b6cd
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: config-batch-order
              env:
                - name: "JOB_NAME"
                  value: "deleteOrderWhereStateIsCanceledJob"
          restartPolicy: OnFailure