apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-account
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-account
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-account
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: service-account
          image: ghcr.io/shashax42/service-account:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config-account
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            limits:
              cpu: 1200m
              memory: 1000Mi
            requests:
              cpu: 600m
              memory: 600Mi